### ISSUE TITLE
no install.exe

### ISSUE THREAD

**Issue by jonathansoko** [megai2/d912pxy#274]
I have no virus software on, defender is off firewall is off... nothing is on... even on the github page when i click into the installer folder, there is no .exe

**Comment by IsmetBesic** [comment]
> [...] even on the github page when i click into the installer folder, there is no .exe

What you see in the github repository is the .cpp source file of the install.exe - the build script is configured to compile it into the "install.exe". 

Have you peeked inside the downloaded zip prior to unzipping? Because when looking into the latest build, one can see that the "install.exe" is part of the zipped release. 

![image](https://user-images.githubusercontent.com/8492994/88769921-58411980-d17d-11ea-9ec0-4c6fec60b793.png)

**Comment by megai2** [comment]
You need to download release, not source code, from here https://github.com/megai2/d912pxy/releases
