### ISSUE TITLE
The overlay shows "DX12: 0 0 0 0 0 0".  Is this because my CPU lacks AVX support?

### ISSUE THREAD

**Issue by BenKennish** [megai2/d912pxy#376]
Hi there,

I have d912pxy v2.4.3.2 installed using the "GW2 Addon Updater" (GW2-AOAOM) and it seems to be running fine (after the textures are generated for the first time) but I notice the overlay always shows

"DX12: 0 0 0 0 0 0".

Does this mean that the game is not actually using DirectX 12 because my CPU is an i7-860 which seems to lack AVX support?  If so, is there any point in me running d912pxy with my CPU at all ?

Thanks in advance,
Ben

**Comment by juhovi** [comment]
2.4.3.2 does not use AVX; the author stopped including AVX versions because they don't bring a benefit so that cannot be it.
Reading the Custom configuration section of the Wiki here suggests that all of the overlay's features are disabled by default so that would explain the zeros. Most likely it is working.

**Comment by BenKennish** [comment]
Ah i see so if there were any overlay features enabled there would be 1s in place of the 0s?

**Comment by megai2** [comment]
"DX12: 0 0 0 0 0 0" is a number of shaders being compiled by dx12 driver on each thread,
When it is all zero - this means all shaders are compiled for this moment and no more texture/object pop-ins will occur.

**Comment by BenKennish** [comment]
That's good to know.  Thanks both.  Shall I edit the following page to remove the mention of "AVX": https://github.com/megai2/d912pxy/wiki/Installing ?
