### ISSUE TITLE
With Anet moving to dx11 what will happen to d912pxy?  

### ISSUE THREAD

**Issue by bzeeeb** [megai2/d912pxy#394]
Or is it more they will give us to option to switch to dx11 so we can stay on 9 and get the better value out of 12.  Is the jump from 11 to 12 significant?

**Comment by LinearBotSystems** [comment]
So far I know dx 11 multi-threading performance is better then dx12 in some scenarios . Dx 12 has more finer control over the graphic card which is also to some degree is a curse because which developer would make profiles for every available graphic card ?  Dx12 Ultimate also gives raytracing.

There is also words that changing codes to Dx11 instead Dx12 is easier not sure if this is true.

About the future of this project I don't know for Gw2 it will be properly unnecessary after the dx11 update .

Also the author here seem very busy with real-life /work.(me too)

if you can switch between the old and the new is also a question in the stars but properly not because Arena.NET said they will drop support for all who don't have the necessary soft and hardware.

The other add-on will also have the trouble to change to dx11 with their dll injection methods too but so far I read this is the same way possible as it is with dx9 .

Hope this answer it

**Comment by megai2** [comment]
I'm ending support & maintenance for d912pxy for this reason
https://www.patreon.com/posts/journey-end-for-55473062

DX9 will be slowly abandoned/broken after DX11 release (who needs to support legacy code?)

Also it is good to use native DX11 implementation, otherwise if they keep DX9 in client,
and if DX11 will be worse than non native DX9(on DX12 or vk), 
adoption rate will be low and devs will not take 
needed feedback, leaving both DX9 and DX11 in a bad state.

So it is better to leave game to developers.

**Comment by Dave247** [comment]
ANet have said that DX9 support will eventually be deprecated and then removed entirely, though hopefully they drew some inspiration from this project to finally get around to making the change.
Maybe someone could look to starting a new project for DX11 > 12 but I don't think there's really much point as any gains would likely be really minimal.

> Eventually the DirectX9 renderer will be deprecated then removed as the new renderer becomes stable.
https://www.guildwars2.com/en/news/directx11-support-is-coming-to-guild-wars-2/
